import type { Player, School, Video, Challenge, ContactRequest, Notification, Sport } from "./types"

export const sports: Sport[] = [
  { id: "football", name: "Football", icon: "⚽" },
  { id: "rugby", name: "Rugby", icon: "🏉" },
  { id: "netball", name: "Netball", icon: "🏀" },
  { id: "athletics", name: "Athletics", icon: "🏃" },
  { id: "cricket", name: "Cricket", icon: "🏏" },
  { id: "basketball", name: "Basketball", icon: "🏀" },
  { id: "hockey", name: "Hockey", icon: "🏑" },
  { id: "swimming", name: "Swimming", icon: "🏊" },
]

export const provinces = [
  "Gauteng",
  "Western Cape",
  "KwaZulu-Natal",
  "Eastern Cape",
  "Free State",
  "Limpopo",
  "Mpumalanga",
  "North West",
  "Northern Cape",
]

export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Thabo Mokoena",
    age: 16,
    gender: "Male",
    region: "Johannesburg",
    province: "Gauteng",
    sports: [sports[0], sports[3]],
    positions: ["Striker", "Sprinter"],
    school: {
      id: "1",
      name: "Pretoria Boys High",
      city: "Pretoria",
      province: "Gauteng",
      email: "info@pbhs.co.za",
      phone: "012-123-4567",
      verificationStatus: "verified",
      coaches: [],
      players: [],
      teams: [],
    },
    guardian: {
      id: "1",
      name: "Sarah Mokoena",
      email: "sarah@email.com",
      phone: "082-123-4567",
      relationship: "Mother",
      verified: true,
    },
    status: "active",
    lastActive: "2024-01-15",
    stats: { speed: 85, power: 72, agility: 88, technique: 79, endurance: 81 },
    videos: [],
    challenges: [],
    privacySettings: { visibleToScouts: true, hideSchoolName: false, guardianApprovalRequired: true },
  },
  {
    id: "2",
    name: "Lerato Dlamini",
    age: 14,
    gender: "Female",
    region: "Cape Town",
    province: "Western Cape",
    sports: [sports[2]],
    positions: ["Goal Shooter"],
    school: {
      id: "2",
      name: "Bishops Diocesan College",
      city: "Cape Town",
      province: "Western Cape",
      email: "info@bishops.org.za",
      phone: "021-123-4567",
      verificationStatus: "verified",
      coaches: [],
      players: [],
      teams: [],
    },
    guardian: {
      id: "2",
      name: "Peter Dlamini",
      email: "peter@email.com",
      phone: "083-234-5678",
      relationship: "Father",
      verified: true,
    },
    status: "active",
    lastActive: "2024-01-14",
    stats: { speed: 78, power: 68, agility: 92, technique: 85, endurance: 76 },
    videos: [],
    challenges: [],
    privacySettings: { visibleToScouts: true, hideSchoolName: true, guardianApprovalRequired: true },
  },
  {
    id: "3",
    name: "Sipho Nkosi",
    age: 17,
    gender: "Male",
    region: "Durban",
    province: "KwaZulu-Natal",
    sports: [sports[1], sports[4]],
    positions: ["Fly-half", "All-rounder"],
    school: {
      id: "3",
      name: "Glenwood High School",
      city: "Durban",
      province: "KwaZulu-Natal",
      email: "info@glenwood.co.za",
      phone: "031-123-4567",
      verificationStatus: "verified",
      coaches: [],
      players: [],
      teams: [],
    },
    guardian: {
      id: "3",
      name: "Grace Nkosi",
      email: "grace@email.com",
      phone: "084-345-6789",
      relationship: "Mother",
      verified: true,
    },
    status: "active",
    lastActive: "2024-01-13",
    stats: { speed: 82, power: 85, agility: 78, technique: 88, endurance: 84 },
    videos: [],
    challenges: [],
    privacySettings: { visibleToScouts: true, hideSchoolName: false, guardianApprovalRequired: true },
  },
  {
    id: "4",
    name: "Nomvula Zulu",
    age: 15,
    gender: "Female",
    region: "Bloemfontein",
    province: "Free State",
    sports: [sports[3]],
    positions: ["Long Jump", "100m"],
    guardian: {
      id: "4",
      name: "James Zulu",
      email: "james@email.com",
      phone: "085-456-7890",
      relationship: "Father",
      verified: true,
    },
    status: "active",
    lastActive: "2024-01-12",
    stats: { speed: 94, power: 75, agility: 89, technique: 82, endurance: 78 },
    videos: [],
    challenges: [],
    privacySettings: { visibleToScouts: true, hideSchoolName: false, guardianApprovalRequired: true },
  },
  {
    id: "5",
    name: "Kagiso Molefe",
    age: 16,
    gender: "Male",
    region: "Polokwane",
    province: "Limpopo",
    sports: [sports[0], sports[5]],
    positions: ["Midfielder", "Point Guard"],
    school: {
      id: "4",
      name: "Capricorn High School",
      city: "Polokwane",
      province: "Limpopo",
      email: "info@capricorn.co.za",
      phone: "015-123-4567",
      verificationStatus: "pending",
      coaches: [],
      players: [],
      teams: [],
    },
    guardian: {
      id: "5",
      name: "Maria Molefe",
      email: "maria@email.com",
      phone: "086-567-8901",
      relationship: "Mother",
      verified: true,
    },
    status: "pending",
    lastActive: "2024-01-11",
    stats: { speed: 80, power: 70, agility: 85, technique: 90, endurance: 82 },
    videos: [],
    challenges: [],
    privacySettings: { visibleToScouts: false, hideSchoolName: true, guardianApprovalRequired: true },
  },
]

export const mockSchools: School[] = [
  {
    id: "1",
    name: "Pretoria Boys High School",
    city: "Pretoria",
    province: "Gauteng",
    email: "info@pbhs.co.za",
    phone: "012-123-4567",
    verificationStatus: "verified",
    coaches: [
      {
        id: "1",
        name: "John Smith",
        email: "jsmith@pbhs.co.za",
        phone: "012-123-4568",
        role: "Head Coach",
        schoolId: "1",
        verified: true,
      },
      {
        id: "2",
        name: "Mary Johnson",
        email: "mjohnson@pbhs.co.za",
        phone: "012-123-4569",
        role: "Assistant Coach",
        schoolId: "1",
        verified: true,
      },
    ],
    players: [],
    teams: [],
  },
  {
    id: "2",
    name: "Bishops Diocesan College",
    city: "Cape Town",
    province: "Western Cape",
    email: "info@bishops.org.za",
    phone: "021-123-4567",
    verificationStatus: "verified",
    coaches: [],
    players: [],
    teams: [],
  },
  {
    id: "3",
    name: "Glenwood High School",
    city: "Durban",
    province: "KwaZulu-Natal",
    email: "info@glenwood.co.za",
    phone: "031-123-4567",
    verificationStatus: "verified",
    coaches: [],
    players: [],
    teams: [],
  },
  {
    id: "4",
    name: "Capricorn High School",
    city: "Polokwane",
    province: "Limpopo",
    email: "info@capricorn.co.za",
    phone: "015-123-4567",
    verificationStatus: "pending",
    coaches: [],
    players: [],
    teams: [],
  },
]

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "U16 Inter-School Match Highlights",
    thumbnail: "/football-match-youth-player.jpg",
    url: "#",
    sport: sports[0],
    type: "match",
    playerId: "1",
    schoolTag: "Pretoria Boys High",
    uploadedAt: "2024-01-14",
    status: "pending",
    duration: "3:24",
  },
  {
    id: "2",
    title: "Sprint Training Session",
    thumbnail: "/athletics-sprint-training.jpg",
    url: "#",
    sport: sports[3],
    type: "training",
    playerId: "4",
    uploadedAt: "2024-01-13",
    status: "approved",
    duration: "2:15",
  },
  {
    id: "3",
    title: "Netball Shooting Drill",
    thumbnail: "/netball-shooting-practice.jpg",
    url: "#",
    sport: sports[2],
    type: "skills",
    playerId: "2",
    schoolTag: "Bishops Diocesan College",
    uploadedAt: "2024-01-12",
    status: "pending",
    duration: "1:45",
  },
  {
    id: "4",
    title: "Rugby Sevens Tournament",
    thumbnail: "/rugby-sevens-youth-match.jpg",
    url: "#",
    sport: sports[1],
    type: "match",
    playerId: "3",
    schoolTag: "Glenwood High School",
    uploadedAt: "2024-01-11",
    status: "approved",
    duration: "5:12",
  },
]

export const mockChallenges: Challenge[] = [
  {
    id: "1",
    title: "Dribbling Challenge",
    sport: sports[0],
    description: "Complete the cone dribbling course in the fastest time possible.",
    rules: ["Use only your feet", "Complete the full course", "Video must show timer"],
    requirements: ["Clear view of entire course", "Visible timer", "Max 60 seconds"],
  },
  {
    id: "2",
    title: "100m Sprint Test",
    sport: sports[3],
    description: "Record your 100m sprint time on a standard track.",
    rules: ["Start from standing position", "No false starts", "Must show finish line"],
    requirements: ["Full track visible", "Timer visible", "Single attempt per submission"],
  },
  {
    id: "3",
    title: "Passing Accuracy Test",
    sport: sports[1],
    description: "Hit 5 targets from various distances with rugby passes.",
    rules: ["5 passes per round", "Mix of short and long passes", "Targets must be visible"],
    requirements: ["All targets visible", "Clear view of throwing technique", "Show score"],
  },
  {
    id: "4",
    title: "Shooting Test",
    sport: sports[2],
    description: "Score as many goals as possible in 60 seconds from the shooting circle.",
    rules: ["Stay within circle", "60 second limit", "Count all successful shots"],
    requirements: ["Full circle visible", "Timer shown", "Clear goal shots"],
  },
]

export const mockContactRequests: ContactRequest[] = [
  {
    id: "1",
    scoutId: "1",
    scoutName: "David Williams",
    scoutOrganization: "Kaizer Chiefs Academy",
    playerId: "1",
    playerName: "Thabo Mokoena",
    guardianId: "1",
    status: "pending",
    message:
      "We are impressed by Thabo's performance in the recent inter-school tournament. We would like to discuss trial opportunities.",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    scoutId: "2",
    scoutName: "Sarah van der Berg",
    scoutOrganization: "Netball SA Development",
    playerId: "2",
    playerName: "Lerato Dlamini",
    guardianId: "2",
    status: "approved",
    message: "Lerato shows exceptional potential. We would like to invite her to our provincial development camp.",
    createdAt: "2024-01-12",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "contact_request",
    title: "New Contact Request",
    message: "David Williams from Kaizer Chiefs Academy has requested contact for Thabo.",
    read: false,
    createdAt: "2024-01-15",
    actionUrl: "/guardian/requests",
  },
  {
    id: "2",
    type: "video_approved",
    title: "Video Approved",
    message: 'Your child\'s video "Sprint Training Session" has been approved and is now visible.',
    read: false,
    createdAt: "2024-01-14",
  },
  {
    id: "3",
    type: "school_link",
    title: "School Link Request",
    message: "Pretoria Boys High School would like to link to your child's profile.",
    read: true,
    createdAt: "2024-01-10",
    actionUrl: "/guardian/settings",
  },
]

export const adminStats = {
  totalPlayers: 2847,
  totalGuardians: 2156,
  totalSchools: 342,
  verifiedScouts: 89,
  pendingVideos: 156,
  weeklyActiveUsers: 1823,
}

export const regionData = [
  { region: "Gauteng", players: 892 },
  { region: "Western Cape", players: 634 },
  { region: "KwaZulu-Natal", players: 521 },
  { region: "Eastern Cape", players: 312 },
  { region: "Free State", players: 198 },
  { region: "Limpopo", players: 156 },
  { region: "Mpumalanga", players: 134 },
]

export const sportData = [
  { sport: "Football", players: 1245 },
  { sport: "Rugby", players: 623 },
  { sport: "Netball", players: 412 },
  { sport: "Athletics", players: 298 },
  { sport: "Cricket", players: 189 },
  { sport: "Basketball", players: 80 },
]
